### PR TITLE
Adding 2 blogposts in the style required

### PR DESCRIPTION
**Pull request by vikasnkumar**
@mohawk2 @duffee  adding a PR for the 2 blog posts I am writing.

Things to note:

*Dec 06*: I think I did it right. The image being referred to at the bottom of the post has Github link though.

*Dec 09*: this references the _previous Dec 06_ post a lot, and since I wrote it as a gist all the links were to the gist. How do you change the links to be relative to the previous Dec 06 post. Maybe you have to do it.

### CODE REVIEW

**Comment by mohawk2** [comment]
Thank you for these, amazing work! I've adjusted that last image to just a relative URL to `banner.jpg` since they're the same image. I also had to adjust the verbatim blocks to not have a ``` but instead 4-space indent, since that's what Statocles demands.

**Comment by mohawk2** [comment]
For the second one, I adjusted the links to previous article to just be `(../../06/finance/)`, and also I changed the `which pdl2` reference to `which perldl` since `pdl2` is now going to be a separate CPAN distro (PDL::Perldl2), since it has heavy external dependencies. I also adjusted the image as above.

**Comment by mohawk2** [comment]
@vikasnkumar Could you look at my adjustments to make sure you're content? I may cherry-pick the first one out separately, but I might not since I want to stay far ahead of the actual date to avoid risk.

@duffee Can you make sure you're happy? I want to minimise how rogue I'm going with this :-)

**Comment by vikasnkumar** [comment]
@mohawk2 everything looks good. thanks for the fixes. i also fixed another reference to `pdl2` with `perldl` in a second commit. looks good to go from my end.

**Comment by vikasnkumar** [comment]
@mohawk2  since this PR was not closed, added the RSS feed link to the layout.

**Pull request closed without merging**
