### PR TITLE
Adding advent post for PDL with D3.js and Mojolicious

### PR DESCRIPTION
**Pull request by duffee**
Includes the example script and css file with a mashup of logos by your truly.

### CODE REVIEW

**Comment by duffee** [comment]
Ready to deploy
fixed #29

**Comment by mohawk2** [comment]
This looks great! Would the `/network.css` not also work as part of the `__DATA__` portion?

**Comment by mohawk2** [comment]
(By the way, the "fix" bit needs to be in either the title, or the first comment on a PR, not in a later one)

**Comment by duffee** [comment]
Yes, there's a bit of css in the DATA section, but it shows both ways of including stylesheets.

I'll merge this and get the next one up today.

**Pull request merged**
